language: rust
cache: cargo
before_script:
- |
  (cargo install rustfmt || true) &&
  export PATH=$HOME:/.local/bin:$PATH &&
  export PATH=$HOME:/.cargo/bin:$PATH
script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test
